### PR TITLE
Update terser to fix problems using latest ECMAScript features

### PR DESCRIPTION
**Pull request by lifeart**
part 3 of https://github.com/stefanpenner/broccoli-concat-analyser/pull/52/files

### CODE REVIEW

**Comment by simonihmig** [comment]
Another rebase here please! 😬

**Comment by lifeart** [comment]
@simonihmig done!

**Review by simonihmig — APPROVED** [review]

**Comment by simonihmig** [comment]
Again, thanks a lot @lifeart for your effort here! Just released this as v5.0.0! :tada: 
/cc @stefanpenner

**Comment by lifeart** [comment]
@simonihmig  Thank you for support and maintenance!

**Pull request merged**
